/**
 * Journal entries, from `src/content/journal`.
 *
 * Generated by `npm run sync:content` from the vault's `journal/{en,fa}` folders. Unlike
 * projects there is no built-in fallback: an empty journal is a legitimate state, so the
 * index renders an empty state and the detail routes simply do not exist.
 */
import { getCollection, render, type CollectionEntry, type RenderResult } from 'astro:content';
import type { Lang } from '../i18n/translations';

/** The renderable MDX body of a journal entry. */
export type JournalContent = RenderResult['Content'];

export interface JournalEntry {
  slug: string;
  title: string;
  date: Date;
  tags: string[];
  /** Frontmatter blurb, used as the list excerpt and the page meta description. */
  summary: string;
}

type JournalEntryRaw = CollectionEntry<'journal'>;

/**
 * `2026-10-07` — locale-independent, matching the format `sync-content` writes into
 * frontmatter. Deliberately not `Intl.DateTimeFormat`: this renders identically in both
 * languages and does not depend on the host's ICU/calendar data.
 */
export function formatEntryDate(date: Date): string {
  return date.toISOString().slice(0, 10);
}

/** `fa/برنامه-هفتگی` → `برنامه-هفتگی`. */
function slugOf(entry: JournalEntryRaw): string {
  if (entry.data.slug) return entry.data.slug;
  const slash = entry.id.lastIndexOf('/');
  return slash === -1 ? entry.id : entry.id.slice(slash + 1);
}

/** See the equivalent check in src/data/projects.ts. */
function assertLanguageMatchesFolder(entry: JournalEntryRaw): void {
  const slash = entry.id.indexOf('/');
  const folder = slash === -1 ? '' : entry.id.slice(0, slash);
  if (folder !== entry.data.lang) {
    throw new Error(
      `Content language mismatch: "${entry.id}" declares lang: ${entry.data.lang} but lives ` +
        `in the "${folder || '(root)'}/" folder. Run \`npm run sync:content\` to rewrite lang ` +
        'from the folder.',
    );
  }
}

function toEntry(entry: JournalEntryRaw): JournalEntry {
  assertLanguageMatchesFolder(entry);
  return {
    slug: slugOf(entry),
    title: entry.data.title,
    date: entry.data.date,
    tags: entry.data.tags,
    summary: entry.data.summary,
  };
}

/** Published journal entries for a language, newest first. */
export async function getJournal(lang: Lang): Promise<JournalEntry[]> {
  const entries = (await getCollection('journal')).filter(
    (entry) => entry.data.lang === lang && !entry.data.draft,
  );
  return entries.map(toEntry).sort((a, b) => b.date.getTime() - a.date.getTime());
}

/** One entry plus its rendered body, or undefined when the slug is unknown. */
export async function getJournalEntryWithContent(
  lang: Lang,
  slug: string,
): Promise<{ entry: JournalEntry; Content: JournalContent } | undefined> {
  const entry = (await getCollection('journal')).find(
    (candidate) =>
      candidate.data.lang === lang && !candidate.data.draft && slugOf(candidate) === slug,
  );
  if (!entry) return undefined;
  const { Content } = await render(entry);
  return { entry: toEntry(entry), Content };
}
