/**
 * Projects, from two possible sources.
 *
 * - **Vault** — `src/content/projects`, generated by `npm run sync:content` from the
 *   Obsidian vault. Frontmatter supplies the card copy; the note body is rendered as MDX.
 *   This is the intended source.
 * - **Built-in** — the copy baked into `src/i18n/translations.ts`. Used only when the vault
 *   collection is empty (a fresh clone, or a vault with no published projects yet), so the
 *   site always builds and never deploys an empty projects section.
 *
 * Pages and views should call the `*Resolved` helpers. The synchronous `getProjects` and
 * friends are the built-in layer, kept as the fallback source.
 */
import { getCollection, render, type CollectionEntry, type RenderResult } from 'astro:content';
import { projectMeta, type ProjectLink, type ProjectSpan } from './site';
import { useTranslations, type Lang, type ProjectCopy } from '../i18n/translations';

export interface Project extends ProjectCopy {
  span: ProjectSpan;
  featured: boolean;
  links?: ProjectLink[];
}

/** Which source a project's copy came from. */
export type ProjectSource = 'vault' | 'builtin';

export interface ResolvedProject extends Project {
  source: ProjectSource;
}

/** The renderable MDX body of a collection entry. */
export type ProjectContent = RenderResult['Content'];

type ProjectEntry = CollectionEntry<'projects'>;

/** `en/vegord` → `vegord` (nested ids keep only the last segment). */
function slugOf(entry: ProjectEntry): string {
  if (entry.data.slug) return entry.data.slug;
  const slash = entry.id.lastIndexOf('/');
  return slash === -1 ? entry.id : entry.id.slice(slash + 1);
}

/**
 * The language folder an entry lives in — the first path segment of its id.
 *
 * The schema already constrains `lang`, but not that it matches the folder. A note filed
 * under `en/` with `lang: fa` would generate a Persian page at an English route, so this
 * fails the build rather than shipping it. `sync:content` rewrites `lang` from the folder,
 * so the only way to hit this is hand-editing a file in `src/content`.
 */
function assertLanguageMatchesFolder(entry: ProjectEntry): void {
  const slash = entry.id.indexOf('/');
  const folder = slash === -1 ? '' : entry.id.slice(0, slash);
  if (folder !== entry.data.lang) {
    throw new Error(
      `Content language mismatch: "${entry.id}" declares lang: ${entry.data.lang} but lives ` +
        `in the "${folder || '(root)'}/" folder. Run \`npm run sync:content\` to rewrite lang ` +
        'from the folder.',
    );
  }
}

/** Published vault projects for one language, newest first. */
async function vaultProjects(lang: Lang): Promise<ResolvedProject[]> {
  const entries = (await getCollection('projects')).filter(
    (entry) => entry.data.lang === lang && !entry.data.draft,
  );

  const dated = entries.map((entry) => {
    assertLanguageMatchesFolder(entry);
    return {
      date: entry.data.date.getTime(),
      project: {
        slug: slugOf(entry),
        name: entry.data.title,
        tagline: entry.data.tagline,
        summary: entry.data.summary,
        // Rendered from the note itself (see getProjectWithContent), not a paragraph list.
        body: [] as string[],
        highlights: entry.data.highlights,
        tags: entry.data.tags,
        span: entry.data.span,
        featured: entry.data.featured,
        links: entry.data.links.length > 0 ? entry.data.links : undefined,
        source: 'vault' as const,
      } satisfies ResolvedProject,
    };
  });

  dated.sort((a, b) => b.date - a.date);
  return dated.map((item) => item.project);
}

/** Every published project for a language, vault-first with the built-in copy as fallback. */
export async function getProjectsResolved(lang: Lang): Promise<ResolvedProject[]> {
  const fromVault = await vaultProjects(lang);
  if (fromVault.length > 0) return fromVault;
  return getProjects(lang).map((project) => ({ ...project, source: 'builtin' as const }));
}

/** Projects flagged `featured` — the home-page bento grid. */
export async function getFeaturedProjectsResolved(lang: Lang): Promise<ResolvedProject[]> {
  return (await getProjectsResolved(lang)).filter((project) => project.featured);
}

/**
 * A single project plus its rendered note body.
 *
 * `Content` is present only for vault-backed projects; the built-in copy carries its body as
 * plain paragraphs on `project.body` instead. Detail pages render whichever is present, so
 * this never returns a project with neither.
 */
export async function getProjectWithContent(
  lang: Lang,
  slug: string,
): Promise<{ project: ResolvedProject; Content?: ProjectContent } | undefined> {
  const project = (await getProjectsResolved(lang)).find((item) => item.slug === slug);
  if (!project) return undefined;
  if (project.source === 'builtin') return { project };

  const entry = (await getCollection('projects')).find(
    (candidate) => candidate.data.lang === lang && slugOf(candidate) === slug,
  );
  if (!entry) return { project };

  const { Content } = await render(entry);
  return { project, Content };
}

/** Every built-in project, localised, in the order declared in `projectMeta`. */
export function getProjects(lang: Lang): Project[] {
  const copy = useTranslations(lang).projects.items;

  return projectMeta.map((meta) => {
    const localized = copy.find((item) => item.slug === meta.slug);
    if (!localized) {
      throw new Error(`Missing "${lang}" copy for project "${meta.slug}"`);
    }
    return {
      ...localized,
      span: meta.span,
      featured: meta.featured,
      links: meta.links,
    };
  });
}

export function getProject(lang: Lang, slug: string): Project | undefined {
  return getProjects(lang).find((project) => project.slug === slug);
}

export function getFeaturedProjects(lang: Lang): Project[] {
  return getProjects(lang).filter((project) => project.featured);
}
